spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/batch
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always